
SOURCES = writer.cpp m3reader.cpp $(HELIUM)/os/usbHid.cpp  $(HELIUM)/math/crc.cpp $(HELIUM)/hiddevice/crcException.cpp

NOCCACHE=1


PROGS=util/m3writer
#LIBS= -ludev
USEUSB=1
LIBS = -L /opt/local/lib
CPPFLAGS = -I /opt/local/include

include ../../Makehel