VSTONE= $(HELIUM)/vstone/vServoSign.cpp $(HELIUM)/vstone/vsTouchSensor.cpp $(HELIUM)/vstone/vServoSign.cpp 

PSIM = psimul.cpp psimulMain.cpp
#% TEST += 

SOURCES = $(PSIM) $(TINYXML) $(APPLICATION) $(ONEXIT) $(V4GSIMUL) $(MOTOR) $(SENSOR) $(GYRO) $(HELIUM)/vstone/vServoSign.cpp
USEODE = 1
PROGS=papp/psimul2

include ../../Makehel



