THIRD= ../../third
PPATH = ..
MATH= $(PPATH)/math/matrixUtil.cpp
TINYXML= $(THIRD)/tinyxml/tinyxml.cpp $(THIRD)/tinyxml/tinyxmlparser.cpp $(THIRD)/tinyxml/tinyxmlerror.cpp $(THIRD)/tinyxml/tinystr.cpp

SOURCES = main.cpp boxNode.cpp jointParser.cpp convexModel.cpp convexModelXml.cpp $(TINYXML) $(MATH)

PROGS=convex

CPPFLAGS = -g -Wall -I $(PPATH) -I $(THIRD) 

include ../Makearch