NOCCACHE=1
VSTONE= $(HELIUM)/vstone/vServo.cpp $(HELIUM)/vstone/vsTouchSensor.cpp $(HELIUM)/vstone/vServoSign.cpp 

PSIM = psimul.cpp psimulMain.cpp
% TEST += 

SOURCES = $(PSIM) $(TINYXML) $(APPLICATION) $(ONEXIT) $(V4GSIMUL) $(MOTOR) $(SENSOR)
USEODE = 1
PROGS=papp/psimul2

include ../../Makehel



